import * as React from 'react';
import { ReportModel } from '../reportModel';
import { ReportSection } from '../primitives';

interface AppendixSectionProps {
  data: ReportModel;
}

export function AppendixSection({ data }: AppendixSectionProps) {
  return (
    <ReportSection title="Phụ lục" number={14}>
      <div className="space-y-6 text-sm text-gray-600">
        <div>
          <h3 className="font-bold text-gray-900 mb-2">Công cụ phân tích sử dụng</h3>
          <ul className="list-disc pl-5 space-y-1">
            <li>Lighthouse (Google Chrome) - Hiệu suất, SEO, Trợ năng, Tiêu chuẩn Web</li>
            <li>Wappalyzer - Công nghệ lõi</li>
            <li>axe-core - Kiểm tra trợ năng chuyên sâu</li>
            <li>WebLens AI - Phân tích, phân loại và đề xuất hướng khắc phục</li>
          </ul>
        </div>
        
        <div>
          <h3 className="font-bold text-gray-900 mb-2">Thông tin Báo cáo</h3>
          <p>
            Báo cáo này được tự động tạo vào <strong>{data.generatedAtFormatted}</strong>. 
            Các chỉ số có thể thay đổi tùy thuộc vào thời điểm truy cập, tốc độ mạng, cấu hình thiết bị tải trang và thay đổi trên mã nguồn của website.
          </p>
        </div>
        
        <div className="pt-4 border-t border-gray-100 text-xs text-gray-400 text-center">
          Generated by WebLens - Web Audit & Performance Analysis Platform
        </div>
      </div>
    </ReportSection>
  );
}
